services:
  - type: web
    name: telegram-paid-subscription-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: ADMIN_ID
        sync: false

      - key: DATA_FILE
        value: data.json
